config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'welcome#index'
  get '/about', to: 'about#index'
  get '/photos', to: 'photos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, :description, :genre, :url, presence: true
  # validates :description, presence: true
  # validates :genre, presence: true
  # validates :url, presence: true

  def self.get_all_photos(genre)
    where(genre: genre)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.get_all_photos(params[:genre])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
<!-- Add image for home button -->
  <a class="home navbar-brand" href="<%= root_path %>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="about nav-link" href="<%= about_path %>">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="photos nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Photos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Landscapes', photos_path(genre: "landscape"), class: "dropdown-item"%>
          <%= link_to 'People', photos_path(genre: "people"), class: "dropdown-item"%>
          <%= link_to 'Space', photos_path(genre: "space"), class: "dropdown-item"%>
          <%= link_to 'Sunsets', photos_path(genre: "sunset"), class: "dropdown-item"%>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<% if @photos.first.genre == "space" %>
  <h2 class="center pad-25-bottom pad-25-top"><%= @photos.first.genre.capitalize %></h2>
<% else %>
  <h2 class="center pad-25-bottom pad-25-top"><%= @photos.first.genre.capitalize.pluralize %></h2>
<% end %>

<div class="container">
  <div class="row justify-content-md-center">
   <div class="image-wrapper">
      <img src="/assets/<%= params[:genre] %>.jpg" alt="Background Image">
    </div>
  </div>
  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-sm-4">
        <div class="card photo-card">
          <div class="index-images">
            <%= image_tag("#{photo.url}", :alt => "Picture missing") %>
          </div>
          <div class="photo-index-title">
            <%= photo.title %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
   <div class="image-wrapper">
      <img src="/assets/home.jpg" alt="Reflection">
    </div>
    <div class="col-md-6 center">
      <h1>Dani Coleman - Through the Lens of Light</h1>
      <br>
      <p>Here is how I see the world and its infinite vastness!</p>
    </div>
  </div>
</div>